application: power-card-viewer
version: 1
runtime: python
api_version: 1

handlers:
  
- url: /iui
  static_dir: iui

- url: /images
  static_dir: images

- url: /stylesheets
  static_dir: stylesheets

- url: .*
  script: main.py
